version: '3.4'
services:
  
  marketanalyzer-crawler:
    environment:
      - DOTNET_ENVIRONMENT=Development
      
      # Web Proxy
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}

      # Database Connection
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres-marketanalyzer
      - DB_PORT=5432
      - DB_NAME=market-analyzer
  
  postgres:
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=market-analyzer
    hostname: postgres-marketanalyzer
    ports:
      - 5432:5432