version: '3.4'

services:
  marketanalyzer-crawler:
    image: ${DOCKER_REGISTRY-}marketanalyzercrawler
    build:
      context: .
      dockerfile: MarketAnalyzer.Crawler/Dockerfile
      args:
        NUGET_REGISTRY: ${NUGET_REGISTRY}
    networks:
      - market-net
    links:
      - postgres
    volumes:
      - ./MarketAnalyzer.Crawler/Configuration:/app/Configuration
  
  postgres:
    image: postgres:latest
    networks:
      - market-net
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data/

  grafana:
    image: ${DOCKER_REGISTRY-}marketanalyzergrafana
    build:
      context: .\grafana
    networks:
      - market-net


networks:
  market-net:
    name: market-net