apiVersion: 1

deleteDatasources:
  - name: PostgreSQL

datasources:
  - name: PostgreSQL
    isDefault: true
    type: postgres
    url: postgres-marketanalyzer:5432
    database: market-analyzer
    user: $DB_USER
    secureJsonData:
      password: $DB_PASSWORD
    jsonData:
      sslmode: "disable"