{
 "title": "MarketAnalyzer",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Лидеры роста/падения", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Рост цены (TOP 100)",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select hahaha.name,\r\n    round((hahaha.current - hahaha.min)::numeric / hahaha.min, 3 ) * 100 as mindiff,\r\n    hahaha.min,\r\n    hahaha.current\r\nfrom\r\n(\r\n    select minmax.*,\r\n    cur.price as current\r\nfrom\r\n(\r\n    select\r\n      itm.\"Id\" as id,\r\n      itm.\"Name\" as name,\r\n      min(ii.\"BasePrice\") as min\r\n    from \"ItemIndicators\" as ii\r\n    join \"Items\" as itm\r\n      on itm.\"Id\" = ii.\"ItemId\"\r\n    join \"JobRuns\" as job\r\n      on job.\"Id\" = ii.\"JobRunId\"\r\n    group by itm.\"Id\"\r\n) as minmax\r\njoin\r\n(\r\n    select\r\n      ii2.\"ItemId\" as id,\r\n      ii2.\"BasePrice\" as price\r\n    from \"ItemIndicators\" as ii2\r\n    join (select max(jb.\"Id\") as id from \"JobRuns\" as jb) as jb2\r\n      on jb2.id = ii2.\"JobRunId\"\r\n) as cur\r\n  on cur.id = minmax.id\r\n) as hahaha\r\norder by mindiff desc\r\nlimit 100"
    }
   ]
  },
  {
   "title": "Падение цены (TOP 100)",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select hahaha.name,\r\n    round((hahaha.max - hahaha.current)::numeric / hahaha.max, 3 ) * 100 as maxdiff,\r\n    hahaha.max,\r\n    hahaha.current\r\nfrom\r\n(\r\n    select minmax.*,\r\n    cur.price as current\r\nfrom\r\n(\r\n    select\r\n      itm.\"Id\" as id,\r\n      itm.\"Name\" as name,\r\n      max(ii.\"BasePrice\") as max\r\n    from \"ItemIndicators\" as ii\r\n    join \"Items\" as itm\r\n      on itm.\"Id\" = ii.\"ItemId\"\r\n    join \"JobRuns\" as job\r\n      on job.\"Id\" = ii.\"JobRunId\"\r\n    group by itm.\"Id\"\r\n) as minmax\r\njoin\r\n(\r\n    select\r\n      ii2.\"ItemId\" as id,\r\n      ii2.\"BasePrice\" as price\r\n    from \"ItemIndicators\" as ii2\r\n    join (select max(jb.\"Id\") as id from \"JobRuns\" as jb) as jb2\r\n      on jb2.id = ii2.\"JobRunId\"\r\n) as cur\r\n  on cur.id = minmax.id\r\n) as hahaha\r\norder by maxdiff desc\r\nlimit 100"
    }
   ]
  },
  { "title": "Графики роста", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Заточки",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\r\n  itm.\"Name\" as metric,\r\n  ii.\"BasePrice\" as value,\r\n  $__time(job.\"RunDate\")\r\nfrom \"ItemIndicators\" as ii\r\njoin \"Items\" as itm\r\n  on itm.\"Id\" = ii.\"ItemId\"\r\njoin \"JobRuns\" as job\r\n  on job.\"Id\" = ii.\"JobRunId\"\r\nwhere $__timeFilter(job.\"RunDate\")\r\nand itm.\"Id\" in (4997, 4998)\r\norder by job.\"RunDate\" asc"
    }
   ]
  },
  {
   "title": "Порошки",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\r\n  itm.\"Name\" as metric,\r\n  ii.\"BasePrice\" as value,\r\n  $__time(job.\"RunDate\")\r\nfrom \"ItemIndicators\" as ii\r\njoin \"Items\" as itm\r\n  on itm.\"Id\" = ii.\"ItemId\"\r\njoin \"JobRuns\" as job\r\n  on job.\"Id\" = ii.\"JobRunId\"\r\nwhere $__timeFilter(job.\"RunDate\")\r\nand itm.\"Id\" in (5951,\r\n5952,\r\n5953,\r\n5954,\r\n5955,\r\n5956,\r\n5957,\r\n5958,\r\n5959,\r\n5960,\r\n5961,\r\n5962,\r\n5963\r\n)\r\norder by job.\"RunDate\" asc"
    }
   ]
  },
  {
   "title": "Кристалл духа",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\r\n  itm.\"Name\" as metric,\r\n  ii.\"BasePrice\" as value,\r\n  $__time(job.\"RunDate\")\r\nfrom \"ItemIndicators\" as ii\r\njoin \"Items\" as itm\r\n  on itm.\"Id\" = ii.\"ItemId\"\r\njoin \"JobRuns\" as job\r\n  on job.\"Id\" = ii.\"JobRunId\"\r\nwhere $__timeFilter(job.\"RunDate\")\r\nand itm.\"Id\" in (15626)\r\norder by job.\"RunDate\" asc"
    }
   ]
  }
 ]
}